[user]
email = "shinta@gx14ac.com"
name = "Shintaro Okumura"

[signing]
backend = "gpg"
behavior = "own"

[aliases]
b = ["branch"]
n = ["new"]

[template-aliases]
"format_timestamp(timestamp)" = "timestamp.ago()"

[ui]
default-command = "log"
